### ISSUE TITLE
Pantry is flooding terminal with debug output when running stack with `--verbose`

### ISSUE THREAD

**Issue by danbroooks** [commercialhaskell/pantry#44]
When running `stack build --verbose`, there is a lot of output coming from what looks like the result of the `show` instance for `RawSnapshotLayer`. 

![Screenshot from 2021-12-04 00-46-23](https://user-images.githubusercontent.com/2951404/144689969-e0c127f5-1b16-41dd-b765-221c4cb44248.png)

I have taken a look through and I think I have tracked it back to this line in pantry:

https://github.com/commercialhaskell/pantry/blob/ac0a31956f2c56cecb88e8c197986b6172e1162e/src/Pantry.hs#L1205

Would it be possible to remove this line from Pantry? Or alternatively implement some debug output here that is a bit more concise? Running `stack build --verbose` on stack itself floods my terminal with output from this line (see above screenshot), and the output itself doesn't seem particularly helpful, unless it was being run on a fairly compact instance of `RawSnapshotLayer`.

Potentially here though there could still be some useful logging to keep in for debugging pantry/stack?

I would be happy to work on a PR to make this change happen :+1:

**Comment by qrilka** [comment]
I think fixing this is a good thing but I don't have a concrete idea what to substitute it with (output only some portion of this data structure?)

**Comment by danbroooks** [comment]
@qrilka how about something that mirrors the `ToJSON` instance?

So given an RSL of:

```
name: 'test'
resolver: lts-2.10
packages:
  - one-0.0.1
drop-packages:
  - drop-package
flags:
  library-only:
    default: false
hidden:
  key: true
ghc-options:
  one:
    - -j
publish-time: 2021-05-19T00:00:00.000Z
```

It would print something like:

```
[Debug] RawSnapshotLayer:
[Debug]   resolver: lts-2.10
[Debug]   packages:
[Debug]     - one-0.0.1 (from Hackage)
[Debug]   drop-packages:
[Debug]     - drop-package
[Debug]   flags:
[Debug]     - library-only: [default:False]
[Debug]   hidden:
[Debug]     - key: True
[Debug]   ghc-options:
[Debug]     one:
[Debug]       - -j
[Debug]   publish-time: 2021-05-19 00:00:00 UTC
```

I spiked this today, though I'm not sure it's the cleanest (I am not used to using `display` from `RIO`). I'm sure with some cleanup it could be PR ready? If you like the look of the above I can do some cleanup and then submit this?

**Comment by qrilka** [comment]
@danbroooks will this change the output size? I think the main problem is the number of snapshot packages and it doesn't look that your proposal will change it much. Or maybe putting every package on its own line changes the situation?

**Comment by danbroooks** [comment]
@qrilka yeah I think you're right, it would still be quite lengthy output still...

**Comment by mpilgrem** [comment]
How about this solution:

`pantry`: `Pantry` exports additional functions `loadAndCompleteSnapshot'` and `loadAndCompleteSnapshotRaw'` that include an initial `Bool` argument to allow the toggling of the debug output of the raw snapshot layer. This would not affect the existing Pantry API.

`stack`: Stack makes use of the additional function `loadAndCompleteSnapshotRaw'` in `Stack.Lock.lockCachedWanted` and  `Stack.SourceMap.loadProjectSnapshotCandidate`. It also provides a new command line option `--[no-]rsl-in-log` (akin to `--[no-]time-in-log`) which will turn off/on the debug output of the raw snapshot layer. Personally, I would make 'turn off' the default.

**Comment by snoyberg** [comment]
Sounds like a good solution. Just mentioning one other possibility: we could add some login inside Stack to set the log level for Pantry to Info even when `--verbose` is in place. It would be easiest to make such a change with some added functionality in `rio` itself.

I have no horse in the race, I'll review your PR @mpilgrem and leave it to you to decide which approach you prefer.

**Comment by mpilgrem** [comment]
@snoyberg, many thanks. Having considered it further, at the moment, having Pantry expose a couple of additional functions seems to me to be the path of least resistance, for the reasons that I set out below.

By way of additional context, Cabal (the library) has the concept of 'deafening' that is 'beyond verbose' - see  https://hackage.haskell.org/package/Cabal-3.8.1.0/docs/Distribution-Verbosity.html. The problem here is that there are other `logDebug` calls in `loadAndCompleteShapshotRaw` (or `loadAndCompleteSnapshot`) (via the functions they use) which are useful, and people would probably want to retain those when debugging. It is only the 'deafening' `logDebug $ fromString $ show rsl` that is problematic.

On changing the log level in the local environment to be greater than 'debug' when calling `loadAndCompleteShapshotRaw`, the problem is that would throw the baby of the other useful `logDebug` messages out with the bathwater of the one 'deafening' message.

On the `rio` package, `RIO.LogLevel` currently has (exported) constructors `LevelDebug` < `LevelInfo` < `LevelWarn` < `LevelError` < `LevelOther !Text` (via `deriving Ord`) and `RIO.Prelude.Logger.simpleLogFunc` (not exported, but used by `newLogFunc`) uses `when (level >= logLevel) do ...`. Making use of existing `LevelOther "Deafening"` (say) is no good (without introducing a lot of complexity elsewhere), because it needs to be smaller than `LevelDebug` and it would be greater than `LevelError` (by default).

One could introduce a new data constructor for `LogLevel` that is smaller than `LevelDebug` (`LevelDeafening`, perhaps). However, changing a key data type involved in logging would be a pretty major breaking change for users of the `rio` package. I am conscious that, on Hackage, `pantry` is shown as having only one reverse dependency, while `rio` has 66. It seems to me that stability of the `rio` API is more important than the debugging output from Pantry and Stack.
